const $=s=>document.querySelector(s);
const KEY={users:'vv_clean_users_v1',session:'vv_clean_session_v1',waste:'vv_clean_waste_v1',lang:'vv_clean_lang_v1'};
let lang=localStorage.getItem(KEY.lang)||'pt';
let deferredPrompt=null;
const T={
pt:{title:'Inteligência de resíduos para uma economia circular real',sub:'Registre, qualifique e localize fluxos de resíduos com dados técnicos, prioridade e rastreabilidade.',login:'Entrar',register:'Registrar',email:'E-mail',password:'Senha',name:'Nome / empresa',cnpj:'CNPJ',city:'Cidade',state:'Estado',wrong:'E-mail ou senha incorretos.',created:'Conta criada. Agora você pode entrar.',installTitle:'Instalar no telefone',installText:'Acesso rápido em tela cheia, direto pelo ícone Vida Verde.',install:'Instalar aplicativo',support:'Suporte oficial Vida Verde',dashboard:'Registro de fluxos de resíduos',add:'Adicionar fluxo',logout:'Sair',search:'Buscar',allTypes:'Todos os tipos',allStatus:'Todos os status',allPriority:'Todas as prioridades',streams:'Fluxos',cities:'Cidades',urgent:'Urgentes',quantity:'Quantidade total',type:'Tipo de resíduo',qty:'Quantidade',unit:'Unidade',moisture:'Umidade',status:'Status',priority:'Prioridade',spec:'Especificação / composição',problem:'Problema atual',expect:'Expectativa / solução desejada',notes:'Observações',save:'Salvar',cancel:'Cancelar',edit:'Editar',remove:'Excluir',confirmDelete:'Excluir este fluxo?',empty:'Nenhum fluxo encontrado.',normal:'Normal',urgentP:'Urgente',newS:'Novo',verified:'Verificado',available:'Disponível',analysis:'Em análise',contracted:'Contratado',installHow:'Como instalar',alreadyInstalled:'O aplicativo já está instalado neste dispositivo.'},
en:{title:'Waste intelligence for a real circular economy',sub:'Register, qualify and locate waste streams with technical data, priority and traceability.',login:'Login',register:'Register',email:'Email',password:'Password',name:'Name / company',cnpj:'CNPJ',city:'City',state:'State',wrong:'Incorrect email or password.',created:'Account created. You can now log in.',installTitle:'Install on phone',installText:'Fast full-screen access from the Vida Verde icon.',install:'Install application',support:'Official Vida Verde support',dashboard:'Waste stream registry',add:'Add stream',logout:'Logout',search:'Search',allTypes:'All types',allStatus:'All statuses',allPriority:'All priorities',streams:'Streams',cities:'Cities',urgent:'Urgent',quantity:'Total quantity',type:'Waste type',qty:'Quantity',unit:'Unit',moisture:'Moisture',status:'Status',priority:'Priority',spec:'Specification / composition',problem:'Current problem',expect:'Expected solution',notes:'Notes',save:'Save',cancel:'Cancel',edit:'Edit',remove:'Delete',confirmDelete:'Delete this stream?',empty:'No streams found.',normal:'Normal',urgentP:'Urgent',newS:'New',verified:'Verified',available:'Available',analysis:'Analysis',contracted:'Contracted',installHow:'How to install',alreadyInstalled:'The app is already installed on this device.'}}
const tr=k=>T[lang][k]||k;
const get=(k,fb=[])=>{try{return JSON.parse(localStorage.getItem(k))??fb}catch{return fb}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const current=()=>get(KEY.users).find(u=>u.id===localStorage.getItem(KEY.session));
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function showModal(title,text){$('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
$('#modalClose').onclick=()=>{$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});
async function installApp(){
  if(matchMedia('(display-mode: standalone)').matches||navigator.standalone){showModal(tr('installTitle'),tr('alreadyInstalled'));return}
  if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;return}
  const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);
  showModal(tr('installHow'),ios?(lang==='pt'?'No Safari: toque em Compartilhar e depois em “Adicionar à Tela de Início”.':'In Safari: tap Share and then “Add to Home Screen”.'):(lang==='pt'?'No Chrome: toque no menu ⋮ e escolha “Instalar aplicativo” ou “Adicionar à tela inicial”.':'In Chrome: tap the ⋮ menu and choose “Install app” or “Add to Home screen”.'));
}
function logo(){return '<img src="assets/logo.png" alt="Vida Verde BioTech LTDA">'}
function auth(mode='login'){
  const users=get(KEY.users);
  $('#app').innerHTML=`<main class="auth"><section class="hero"><div class="logo-card">${logo()}</div><span class="eyebrow">VIDA VERDE TRACE360 · TEST</span><h1>${tr('title')}</h1><p>${tr('sub')}</p></section><section class="auth-side"><div class="card"><div class="toprow"><div class="brandline"><small>VIDA VERDE BIOTECH LTDA</small><strong>Trace360 Waste Intelligence</strong></div><div class="lang"><button data-lang="pt" class="${lang==='pt'?'active':''}">PT</button><button data-lang="en" class="${lang==='en'?'active':''}">EN</button></div></div><div class="tabs"><button id="tabLogin" class="${mode==='login'?'active':''}">${tr('login')}</button><button id="tabReg" class="${mode==='register'?'active':''}">${tr('register')}</button></div><div id="authForm"></div><div class="install-box"><strong>${tr('installTitle')}</strong><span>${tr('installText')}</span><button id="installBtn" class="btn secondary full">${tr('install')}</button></div><div class="support"><b>${tr('support')}</b><br><a href="mailto:contact@vidaverdebiotech.com.br">contact@vidaverdebiotech.com.br</a><br><a href="https://wa.me/5551999261234" target="_blank" rel="noopener">WhatsApp +55 51 99926-1234</a><br><a href="https://www.vidaverdebiotech.com.br" target="_blank" rel="noopener">www.vidaverdebiotech.com.br</a></div></div></section></main>`;
  document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem(KEY.lang,lang);auth(mode)});
  $('#tabLogin').onclick=()=>auth('login');$('#tabReg').onclick=()=>auth('register');$('#installBtn').onclick=installApp;
  if(mode==='login'){
    $('#authForm').innerHTML=`<form id="loginForm"><label>${tr('email')}</label><input name="email" type="email" required autocomplete="username"><label>${tr('password')}</label><input name="password" type="password" required autocomplete="current-password"><div id="msg"></div><button class="btn primary full" style="margin-top:18px">${tr('login')}</button></form>`;
    $('#loginForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const u=users.find(x=>x.email.toLowerCase()===String(f.get('email')).toLowerCase()&&x.password===f.get('password'));if(!u){$('#msg').innerHTML=`<div class="notice error">${tr('wrong')}</div>`;return}localStorage.setItem(KEY.session,u.id);dashboard()};
  }else{
    $('#authForm').innerHTML=`<form id="regForm"><label>${tr('name')}</label><input name="name" required><label>${tr('cnpj')}</label><input name="cnpj"><label>${tr('email')}</label><input name="email" type="email" required autocomplete="username"><label>${tr('password')}</label><input name="password" type="password" minlength="6" required autocomplete="new-password"><div id="msg"></div><button class="btn primary full" style="margin-top:18px">${tr('register')}</button></form>`;
    $('#regForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const email=String(f.get('email')).trim().toLowerCase();if(users.some(u=>u.email===email)){ $('#msg').innerHTML='<div class="notice error">Email already registered.</div>';return }users.push({id:id(),name:String(f.get('name')).trim(),cnpj:String(f.get('cnpj')).trim(),email,password:String(f.get('password')),role:users.length?'entity':'admin'});set(KEY.users,users);$('#msg').innerHTML=`<div class="notice ok">${tr('created')}</div>`;setTimeout(()=>auth('login'),600)};
  }
}
function dashboard(){
  const u=current();if(!u){auth();return}
  const data=get(KEY.waste);
  $('#app').innerHTML=`<div class="app"><header class="topbar"><div class="appbrand">${logo()}<strong>Trace360</strong></div><div class="nav-actions"><div class="lang"><button data-lang="pt" class="${lang==='pt'?'active':''}">PT</button><button data-lang="en" class="${lang==='en'?'active':''}">EN</button></div><button id="logout" class="btn ghost">${tr('logout')}</button></div></header><main class="wrap"><div class="dashboard-head"><div><h2>${tr('dashboard')}</h2><p>${u.name} · ${u.role==='admin'?'Admin':'Entity'}</p></div><button id="add" class="btn primary">+ ${tr('add')}</button></div><section id="metrics" class="metrics"></section><section class="toolbar"><input id="q" class="search" placeholder="${tr('search')}"><select id="typeF"><option value="">${tr('allTypes')}</option></select><select id="statusF"><option value="">${tr('allStatus')}</option><option value="new">${tr('newS')}</option><option value="verified">${tr('verified')}</option><option value="available">${tr('available')}</option><option value="analysis">${tr('analysis')}</option><option value="contracted">${tr('contracted')}</option></select><select id="priorityF"><option value="">${tr('allPriority')}</option><option value="normal">${tr('normal')}</option><option value="urgent">${tr('urgentP')}</option></select><button id="clear" class="btn ghost">×</button></section><section id="streams" class="streams"></section></main></div>`;
  document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem(KEY.lang,lang);dashboard()});
  $('#logout').onclick=()=>{localStorage.removeItem(KEY.session);auth()};$('#add').onclick=()=>streamForm();
  const types=[...new Set(data.map(x=>x.type).filter(Boolean))].sort();$('#typeF').innerHTML+=types.map(x=>`<option>${escapeHtml(x)}</option>`).join('');
  ['q','typeF','statusF','priorityF'].forEach(s=>$('#'+s).oninput=renderStreams);$('#clear').onclick=()=>{$('#q').value='';$('#typeF').value='';$('#statusF').value='';$('#priorityF').value='';renderStreams()};renderMetrics();renderStreams();
}
function renderMetrics(){const data=get(KEY.waste);const cities=new Set(data.map(x=>`${x.city}/${x.state}`).filter(x=>!x.startsWith('/')));const urgent=data.filter(x=>x.priority==='urgent').length;const total=data.reduce((s,x)=>s+(Number(x.qty)||0),0);$('#metrics').innerHTML=`<div class="metric"><b>${data.length}</b><span>${tr('streams')}</span></div><div class="metric"><b>${cities.size}</b><span>${tr('cities')}</span></div><div class="metric"><b>${urgent}</b><span>${tr('urgent')}</span></div><div class="metric"><b>${total.toLocaleString()}</b><span>${tr('quantity')}</span></div>`}
function renderStreams(){
  const q=($('#q')?.value||'').toLowerCase(),tf=$('#typeF')?.value||'',sf=$('#statusF')?.value||'',pf=$('#priorityF')?.value||'';
  let data=get(KEY.waste).filter(x=>(!tf||x.type===tf)&&(!sf||x.status===sf)&&(!pf||x.priority===pf)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));
  $('#streams').innerHTML=data.length?data.map(x=>`<article class="stream"><div><h3>${escapeHtml(x.type)}</h3><div class="meta"><span>${escapeHtml(x.city)}/${escapeHtml(x.state)}</span><span>${escapeHtml(String(x.qty))} ${escapeHtml(x.unit)}</span><span>${tr('moisture')}: ${escapeHtml(x.moisture||'—')}</span><span class="badge ${x.priority==='urgent'?'urgent':''}">${x.priority==='urgent'?tr('urgentP'):tr('normal')}</span><span class="badge">${escapeHtml(statusLabel(x.status))}</span></div>${x.spec?`<p>${escapeHtml(x.spec)}</p>`:''}</div><div class="stream-actions"><button class="btn ghost" data-edit="${x.id}">${tr('edit')}</button><button class="btn danger" data-del="${x.id}">${tr('remove')}</button></div></article>`).join(''):`<div class="card">${tr('empty')}</div>`;
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>streamForm(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeStream(b.dataset.del));
}
function streamForm(editId){
  const data=get(KEY.waste),x=data.find(i=>i.id===editId)||{type:'',qty:'',unit:'t/mês',moisture:'',city:'',state:'RS',status:'new',priority:'normal',spec:'',problem:'',expect:'',notes:''};
  $('#app').innerHTML=`<div class="app"><header class="topbar"><div class="appbrand">${logo()}<strong>Trace360</strong></div><button id="back" class="btn ghost">${tr('cancel')}</button></header><main class="wrap"><div class="card" style="max-width:900px;margin:auto"><h2>${editId?tr('edit'):tr('add')}</h2><form id="streamForm" class="form-grid"><div><label>${tr('type')}</label><input name="type" value="${attr(x.type)}" required></div><div><label>${tr('qty')}</label><input name="qty" type="number" min="0" step="0.01" value="${attr(x.qty)}" required></div><div><label>${tr('unit')}</label><select name="unit"><option ${x.unit==='t/mês'?'selected':''}>t/mês</option><option ${x.unit==='t/ano'?'selected':''}>t/ano</option><option ${x.unit==='kg/mês'?'selected':''}>kg/mês</option><option ${x.unit==='m³/mês'?'selected':''}>m³/mês</option></select></div><div><label>${tr('moisture')}</label><input name="moisture" value="${attr(x.moisture)}" placeholder="ex. 10–15%"></div><div><label>${tr('city')}</label><input name="city" value="${attr(x.city)}" required></div><div><label>${tr('state')}</label><input name="state" maxlength="2" value="${attr(x.state)}" required></div><div><label>${tr('status')}</label><select name="status">${['new','verified','available','analysis','contracted'].map(v=>`<option value="${v}" ${x.status===v?'selected':''}>${statusLabel(v)}</option>`).join('')}</select></div><div><label>${tr('priority')}</label><select name="priority"><option value="normal" ${x.priority==='normal'?'selected':''}>${tr('normal')}</option><option value="urgent" ${x.priority==='urgent'?'selected':''}>${tr('urgentP')}</option></select></div><div class="wide"><label>${tr('spec')}</label><textarea name="spec">${escapeHtml(x.spec)}</textarea></div><div class="wide"><label>${tr('problem')}</label><textarea name="problem">${escapeHtml(x.problem)}</textarea></div><div class="wide"><label>${tr('expect')}</label><textarea name="expect">${escapeHtml(x.expect)}</textarea></div><div class="wide"><label>${tr('notes')}</label><textarea name="notes">${escapeHtml(x.notes)}</textarea></div><div class="wide"><button class="btn primary full">${tr('save')}</button></div></form></div></main></div>`;
  $('#back').onclick=dashboard;$('#streamForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target).entries());const obj={...x,...f,id:editId||id(),qty:Number(f.qty),updatedAt:new Date().toISOString(),owner:current().id};const i=data.findIndex(v=>v.id===editId);if(i>=0)data[i]=obj;else data.unshift(obj);set(KEY.waste,data);dashboard()};
}
function removeStream(i){if(confirm(tr('confirmDelete'))){set(KEY.waste,get(KEY.waste).filter(x=>x.id!==i));renderMetrics();renderStreams()}}
function statusLabel(v){return ({new:tr('newS'),verified:tr('verified'),available:tr('available'),analysis:tr('analysis'),contracted:tr('contracted')})[v]||v}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function attr(v=''){return escapeHtml(v).replace(/`/g,'&#96;')}
if(current())dashboard();else auth();
